# Generated by Django 3.0.4 on 2020-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('number', models.IntegerField()),
                ('term', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
