# Generated by Django 3.0.4 on 2020-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
