# Generated by Django 3.0.4 on 2020-04-23 10:29

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200423_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=course.models.custom_upload_path),
        ),
    ]
