# Generated by Django 3.0.4 on 2020-04-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_chosed',
            field=models.IntegerField(default=0),
        ),
    ]
