# Generated by Django 3.0.4 on 2020-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
