# Generated by Django 3.0.4 on 2020-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_time_chosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
