# Generated by Django 3.0.4 on 2020-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Term',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.AddField(
            model_name='person',
            name='Subject',
            field=models.TextField(null=True),
        ),
    ]
