# Generated by Django 3.0.4 on 2020-03-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20200320_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='isAvailable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
