# Generated by Django 3.0.4 on 2020-03-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=4)),
                ('Number', models.IntegerField()),
                ('Term', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('rating', models.FloatField()),
                ('address', models.CharField(max_length=30)),
                ('courseList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('isAvailable', models.BooleanField()),
                ('price', models.FloatField()),
                ('phoneNumber', models.CharField(max_length=10)),
                ('orderHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.OrderHistory')),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='tutee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.Person'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor', to='Backend.Person'),
        ),
    ]
