# Generated by Django 3.0.4 on 2020-04-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200424_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.IntegerField(),
        ),
    ]
