# Generated by Django 3.0.4 on 2020-04-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('orderhistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('isAvailable', models.BooleanField(null=True)),
                ('price', models.FloatField(null=True)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('orderHistory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhistory.OrderHistory')),
            ],
        ),
    ]
