# Generated by Django 3.0.4 on 2020-04-21 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to=person.models.custom_upload_path)),
            ],
        ),
    ]
