# Generated by Django 3.0.4 on 2020-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isTutor',
            field=models.BooleanField(default=False),
        ),
    ]
