# Generated by Django 3.0.4 on 2020-04-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200419_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isAvailable',
        ),
    ]
