# Generated by Django 3.0.4 on 2020-04-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_profile_isavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
    ]
