# Generated by Django 3.0.4 on 2020-04-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderhistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='isPayed',
        ),
    ]
