# Generated by Django 3.0.4 on 2020-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhistory', '0002_remove_orderhistory_ispayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='paymentId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
